### ISSUE TITLE
Question about loss function of G

### ISSUE THREAD

**Issue by yunjey** [akanazawa/vgan#1]
Hi, 

Thank you for releasing nice paper and code. 
Refer to **Eq (11)**, I think the generator **G** should be trained using mean outputs of the encoder **E**.  However, as can be seen [here](https://github.com/akanazawa/vgan/blob/master/gan_training/train.py#L36) and [here](https://github.com/akanazawa/vgan/blob/master/gan_training/models/resnet.py#L113-L120), **G** is trained using the reparameterization outputs of **E** rathen mean.

Is this intended? Any explanation for the inconsistency between the code and equation?

Thanks, 
Yunjey

**Comment by xbpeng** [comment]
Sorry about the late reply. You are right, the code is applying noise to the encoding when updating the generator, instead of just using the mean. This should not make a big difference, in fact, sampling from the latents is more consistent with the original objective in Equation 7. Updating the generating using only the mean of the encoding was a simplification. In this case, I think either one should work.
